// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzC13DkXY4FDKRqBnNl-Yez5jx4m2So5I',
    appId: '1:6749358419:web:82fbfd9c5ca2e1f97679a6',
    messagingSenderId: '6749358419',
    projectId: 'test-hackathon-69055',
    authDomain: 'test-hackathon-69055.firebaseapp.com',
    storageBucket: 'test-hackathon-69055.firebasestorage.app',
    measurementId: 'G-5P3F4VKS2K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjOWDsestbf7fePcazwbD2q93oNP_0pdo',
    appId: '1:6749358419:android:3e98cbf6c52943d07679a6',
    messagingSenderId: '6749358419',
    projectId: 'test-hackathon-69055',
    storageBucket: 'test-hackathon-69055.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCrQLxZEgy0y_Hw51w26CV2Lnned1qwnQ',
    appId: '1:6749358419:ios:5add6ee50ca786a37679a6',
    messagingSenderId: '6749358419',
    projectId: 'test-hackathon-69055',
    storageBucket: 'test-hackathon-69055.firebasestorage.app',
    iosBundleId: 'com.example.galoresAiApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCrQLxZEgy0y_Hw51w26CV2Lnned1qwnQ',
    appId: '1:6749358419:ios:5add6ee50ca786a37679a6',
    messagingSenderId: '6749358419',
    projectId: 'test-hackathon-69055',
    storageBucket: 'test-hackathon-69055.firebasestorage.app',
    iosBundleId: 'com.example.galoresAiApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzC13DkXY4FDKRqBnNl-Yez5jx4m2So5I',
    appId: '1:6749358419:web:8312427e3a1a27567679a6',
    messagingSenderId: '6749358419',
    projectId: 'test-hackathon-69055',
    authDomain: 'test-hackathon-69055.firebaseapp.com',
    storageBucket: 'test-hackathon-69055.firebasestorage.app',
    measurementId: 'G-HR8EM2613S',
  );

}